const constants = {
  FETCH_MOVIES_STARTED: 'FETCH_MOVIES_STARTED',
  FETCH_MOVIES_ERROR: 'FETCH_MOVIES_ERROR',
  FETCH_MOVIES_COMPLETED: 'FETCH_MOVIES_COMPLETED',
  SORT_BY_RATE: 'SORT_BY_RATE',
  SORT_BY_RELEASE: 'SORT_BY_RELEASE',
  NO_SORT: 'NO_SORT',
  SORT: 'SORT',
  FETCH_MOVIE_BY_ID_STARTED: 'FETCH_MOVIE_BY_ID_STARTED',
  FETCH_MOVIE_BY_ID_ERROR: 'FETCH_MOVIE_BY_ID_ERROR',
  FETCH_MOVIE_BY_ID_COMPLETED: 'FETCH_MOVIE_BY_ID_COMPLETED',
};

export default constants;
